### ISSUE TITLE
enable actions

### ISSUE THREAD

**Issue by CyberGear** [TeleSoftas/git-config-commit-template-ij-plugin#5]
```
name: Scala CI

on:
  push:
    branches: [ 'master', 'github-actions' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generate build number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}        
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Run Tests
      run: ./gradlew scalatest
    - name: Package Plugin
      run: ./gradlew assemble  
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: build/distributions/Git_Config_Commit_Template-1.0-SNAPSHOT.zip

```
